/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connect_hub.ProfileManagment;
import connect_hub.FriendManagment.BlockUser;
import connect_hub.UserManagement.UserDetails;
import connect_hub.UserManagement.PutUsers;
import connect_hub.UserManagement.ReadUsers;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class getListOfFriendsWindow extends javax.swing.JFrame {
String email;
ArrayList<UserDetails> userList ;
    /**
     * Creates new form getListOfFriendsWindow
     */
    public getListOfFriendsWindow(String email) throws NoSuchAlgorithmException, IOException {
        initComponents();
        this.email=email;
        loadAllFriends();
    }

    public getListOfFriendsWindow() {
    }
    
    public void loadAllFriends() throws NoSuchAlgorithmException, IOException{
       userList = new ArrayList<>();
         userList = ReadUsers.readUsersFromFile("users.json");
         UserDetails user=new UserDetails();
         user=user.getSpecificUser(userList, email);
         DefaultListModel<String>listModel=new DefaultListModel<>();
         for(connect_hub.UserManagement.Friends friend:user.getFriends()){
             String friendInfo = "User Name: "+friend.getFriendd() + "        " +" Status:  " + (friend.isStatus() );
        listModel.addElement(friendInfo);
         }
       jList1.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 204, 255));
        jLabel2.setText("List of friends");

        jButton1.setText("remove friend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Block Friend");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int index=jList1.getSelectedIndex();
    userList = new ArrayList<>();
    try {
        userList = ReadUsers.readUsersFromFile("users.json");
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
         UserDetails userSender=new UserDetails();
         userSender=userSender.getSpecificUser(userList, email);
         connect_hub.UserManagement.Friends friend=userSender.getFriends().get(index);
         UserDetails userReciver= new UserDetails();
          userReciver= userReciver.getSpecificUser2(userList, friend.getFriendd());
          BlockUser block=new BlockUser(userSender,userReciver,userList);
    try {
        block.remove(userSender, userReciver,userList);
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        PutUsers.save(userList);
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
            JOptionPane.showMessageDialog(this, "removed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int index=jList1.getSelectedIndex();
    userList = new ArrayList<>();
    try {
        userList = ReadUsers.readUsersFromFile("users.json");
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
         UserDetails userSender=new UserDetails();
         userSender=userSender.getSpecificUser(userList, email);
         connect_hub.UserManagement.Friends friend=userSender.getFriends().get(index);
         UserDetails userReciver= new UserDetails();
          userReciver= userReciver.getSpecificUser2(userList, friend.getFriendd());
          BlockUser block=new BlockUser(userSender,userReciver,userList);
    try {
        block.Block(userSender, userReciver,userList);
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        PutUsers.save(userList);
    } catch (IOException ex) {
        Logger.getLogger(getListOfFriendsWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
            JOptionPane.showMessageDialog(this, "Block successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getListOfFriendsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getListOfFriendsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getListOfFriendsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getListOfFriendsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new getListOfFriendsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
