/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connect_hub.Groups;

import connect_hub.ContentCreation.Content;
import connect_hub.ContentCreation.Post;
<<<<<<< HEAD
import connect_hub.Groups.MemberrequestWindow;
=======
>>>>>>> 5bc3f581823a999bf7e723b97efa6986b9b6402a
import connect_hub.NewsFeed.ViewPostsWindow;
import connect_hub.UserManagement.ReadUsers;
import connect_hub.UserManagement.UserDetails;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PostRequestWindow extends javax.swing.JFrame {
Group g;
String email;
ArrayList<Content>posts;
ArrayList<UserDetails>users;
ArrayList<Group>groups;
GroupRepository r;
    /**
     * Creates new form PostRequestWindow
     */
    public PostRequestWindow(Group g,String email) {
        initComponents();
        this.g=g;
        this.email=email;
        this.groups=new ArrayList<>();
        r=new GroupRepository("groups.json");
        openWindow();
    }

    public PostRequestWindow() {
    }
    public void openWindow(){
        posts=g.getRequestPosts();
      users=new ArrayList<>();
      try {
          users = ReadUsers.readUsersFromFile("users.json");
      } catch (IOException ex) {
          Logger.getLogger(GroupActivites.class.getName()).log(Level.SEVERE, null, ex);
      }
        UserDetails user=new UserDetails();
        user=user.getSpecificUser(users, email);
  
       DefaultListModel<String>listModel=new DefaultListModel<>();
<<<<<<< HEAD
        for(int i=0;i<g.getRequestPosts().size();i++){
=======
        for(int i=0;i<g.getPosts().size();i++){
>>>>>>> 5bc3f581823a999bf7e723b97efa6986b9b6402a
            
             String postInfo = "Post"+i;
            
        listModel.addElement(postInfo);
         }
         jList1.setModel(listModel);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 204, 255));
        jLabel1.setText("Posts requested");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Get post");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(40, 40, 40)
                                .addComponent(jButton2)
                                .addGap(29, 29, 29)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index=jList1.getSelectedIndex();
 if(index==-1){
            JOptionPane.showMessageDialog(this,"Choose Group");
        }
        else{
         Post p=(Post) posts.get(index);
         
         ViewPostsWindow window=new ViewPostsWindow(p);
         window.setVisible(true);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int index=jList1.getSelectedIndex();
 if(index==-1){
            JOptionPane.showMessageDialog(this,"Choose Group");
        }
        else{
   
      groups=r.getAllGroups();
      System.out.println(groups);
      Post post= (Post) posts.get(index);
<<<<<<< HEAD
      Post tmp=new Post();
      for(Group group:groups){
          if(group.getGroupId().equals(g.getGroupId())){
              for(Content postt:group.getRequestPosts()){
                  if(postt.getid().equals(post.getid())){
                      tmp=post;
                       System.out.println("Done");
                            break;
                  }
              }
              group.approvePost(tmp);
              System.out.println(group.getRequestPosts());
          }
      }
           try {
               r.saveGroups(groups);
             
           } catch (IOException ex) {
               Logger.getLogger(PostRequestWindow.class.getName()).log(Level.SEVERE, null, ex);
           }
              openWindow();
            JOptionPane.showMessageDialog(this, "post added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            openWindow();
        
=======
    
      for(int i=0;i<groups.size();i++){
          if(groups.get(i).getGroupId().equals(g.getGroupId())){
              groups.get(i).approvePost(post);
              try {
                  r.saveGroups(groups);
              } catch (IOException ex) {
                  Logger.getLogger(MemberrequestWindow.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
      }
    
>>>>>>> 5bc3f581823a999bf7e723b97efa6986b9b6402a
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
<<<<<<< HEAD
      int index=jList1.getSelectedIndex();
=======
          int index=jList1.getSelectedIndex();
>>>>>>> 5bc3f581823a999bf7e723b97efa6986b9b6402a
 if(index==-1){
            JOptionPane.showMessageDialog(this,"Choose Group");
        }
        else{
<<<<<<< HEAD
   
      groups=r.getAllGroups();
      System.out.println(groups);
      Post post= (Post) posts.get(index);
      Post tmp=new Post();
      for(Group group:groups){
          if(group.getGroupId().equals(g.getGroupId())){
              for(Content postt:group.getRequestPosts()){
                  if(postt.getid().equals(post.getid())){
                      tmp=post;
                       System.out.println("Done");
                            break;
                  }
              }
              group.rejectPost(tmp);
          }
      }
           try {
               r.saveGroups(groups);
             openWindow();
            JOptionPane.showMessageDialog(this, "post rejected successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
           } catch (IOException ex) {
               Logger.getLogger(PostRequestWindow.class.getName()).log(Level.SEVERE, null, ex);
           }
              
              openWindow();
        
=======
       Post p=(Post) posts.get(index);
         g.rejectPost(p);
           JOptionPane.showMessageDialog(this, "Post rejected successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
           openWindow();
>>>>>>> 5bc3f581823a999bf7e723b97efa6986b9b6402a
 }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostRequestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
